fields = {
    "project":{
        "project_id": "Project ID",
        "publish_date": "Publish Date",
        "project_name": "Project Name",
        "project_objectives": "Project Objectives",
        "project_owner": "Project Owner",
        "project_owner_email": "Project Owner Email",
        "principal_investigator": "Principal Investigator",
        "principal_investigator_email": "Principal Investigator Email",
        "project_contact": "Project Contact",
        "project_contact_email": "Project Contact Email",
        "project_latitude": "Project Latitude",
        "project_longitude": "Project Longitude",
        "country_code": "Country Code",
        "project_data_use_and_constraints": "Project Data Use and Constraints"
    },
    "deployment": {
        "camera_deployment_id": "Camera Deployment ID",
        "camera_site_name": "Camera Site Name",
        "actual_longitude": "Actual Longitude",
        "actual_latitude": "Actual Latitude",
        "camera_deployment_begin_date": "Camera Deployment Begin Date",
        "camera_deployment_end_date": "Camera Deployment End Date",
        "bait": "Bait  ",
        "bait_description": "Bait Description",
        "feature": "Feature",
        "feature_methodology": "Feature Methodology",
        "camera_id": "Camera ID",
        "quiet_period_setting": "Quiet Period Setting",
        "camera_failure_details": "Camera Failure Details",
        "sensitivity_setting": "Sensitivity Setting"
    },
    "images":{
        "image_sequence_id": "Image Sequence ID",
        "image_path": "Image path",
        "image_ID": "Image ID",
        "image_file_name": "Image File Name",
        "photo_type": "Photo Type",
        "photo_type_identified_by": "Photo Type Identified by",
        "genus_species": "Genus Species",
        "iucn_id": "IUCN ID",
        "access_constraints": "Access Constraints",
        "date_time": "Date_Time",
        "interest_rank": "Interest Rank",
        "age": "Age",
        "sex": "Sex",
        "individual_id": "Individual ID",
        "count":"Count",
        "animal_recognizable": "Animal recognizable",
        "individual_animal_notes": "individual Animal notes",
        "digital_origin": "Digital Origin",
        "restrictions_on_access": "Restrictions on Access",
        "embargo_period_end_date": "Embargo Period End Date",
        "image_use_restrictions": "Image Use Restrictions"
    },
    "researcher_identifications":{
        "iucn_id": "IUCN ID",
        "sn": "Genus Species",
        "age": "Age",
        "sex":"Sex",
        "individual_id": "Individual ID",
        "animal_recognizable": "Animal recognizable"

    },

}